apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "besu-node.fullname" . }}-config-toml
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "besu-node.labels" . | nindent 4 }}
    app.kubernetes.io/component: config-toml
data:
  config.toml: |-
    # https://besu.hyperledger.org/stable/public-networks/reference/cli/options

    # node
    genesis-file="/opt/besu/genesis.json"
    min-gas-price=0
    host-allowlist=["*"]
    {{- if .Values.node.logging }}
    logging={{ .Values.node.logging | quote }}
    {{- end}}
    #logging="INFO" ## default
    #logging="DEBUG"
    #logging="TRACE"

    # bootnode
    Xdns-enabled=true
    Xdns-update-enabled=true
    bootnodes={{ include "besu-node.bootnodes" . }}

    # jsonrpc http
    rpc-http-enabled=true
    rpc-http-host="0.0.0.0"
    #rpc-http-port=8545 ## default
    rpc-http-api=["ETH", "NET", "WEB3", "ADMIN", "DEBUG", "EEA", "IBFT", "PERM", "PRIV", "QBFT"]
    rpc-http-cors-origins=["*"]

    # jsonrpc ws
    rpc-ws-enabled=true
    rpc-ws-host="0.0.0.0"
    #rpc-ws-port=8546 ## default
    rpc-ws-api=["ETH", "NET", "WEB3", "ADMIN", "DEBUG", "EEA", "IBFT", "PERM", "PRIV", "QBFT"]

    # graphql http
    #graphql-http-enabled=false ## default
    #graphql-http-host="0.0.0.0"
    #graphql-http-port=8547 #default
    #graphql-http-cors-origins=["*"]
