apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.network.name }}-{{ .Values.node.name }}-private-key
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: private-key
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
stringData:
  key: |-
    {{ .Values.node.privateKey | trim }}
