apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "besu-node.fullname" . }}-public-key
  labels:
    {{- include "besu-node.labels" . | nindent 4 }}
data:
  key.pub: {{ .Values.node.publicKey | trim | quote }}
