apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "besu-node.fullname" . }}
  labels:
    {{- include "besu-node.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "besu-node.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "besu-node.fullname" . }}
  #replicas: 1 #default
  #minReadySeconds: 0 #default
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "besu-node.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      #serviceAccountName: {{ include "besu-node.fullname" . }}
      #terminationGracePeriodSeconds: 10
      {{- with .Values.node.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.node.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.node.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: besu-volume-permission
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /opt/besu/database"]
        volumeMounts:
        - name: data
          mountPath: /opt/besu/database
        securityContext:
          runAsUser: 0
      containers:
      - name: besu
        image: "{{ .Values.node.image.repository }}:{{ .Values.node.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 8545
          name: rpc-http
        - containerPort: 8546
          name: rpc-ws
        - containerPort: 8547
          name: rpc-graphql
        - containerPort: 30303
          name: rlpx
        - containerPort: 30303
          name: discovery
          protocol: UDP
        volumeMounts:
        - name: genesis-json
          mountPath: /opt/besu/genesis.json
          subPath: genesis.json
          readOnly: true
        - name: private-key
          mountPath: /opt/besu/key
          subPath: key
          readOnly: true
        - name: config-toml
          mountPath: /opt/besu/config.toml
          subPath: config.toml
          readOnly: true
        - name: data
          mountPath: /opt/besu/database
        #command:
        args: [--config-file=config.toml]
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 1Gi
        #   limits:
        #     cpu: 500m
        #     memory: 2Gi
      volumes:
      - name: genesis-json
        configMap:
          name: {{ include "besu-node.fullname" . }}-genesis-json
      - name: private-key
        secret:
          secretName: {{ include "besu-node.fullname" . }}-private-key
      - name: config-toml
        configMap:
          name: {{ include "besu-node.fullname" . }}-config-toml
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      {{- if .Values.node.storageClassName }}
      storageClassName: {{ .Values.node.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.node.storage }}
