kubectl delete -f validator-4
kubectl delete -f validator-3
kubectl delete -f validator-2
kubectl delete -f validator-1
kubectl delete -f bootnode-1
kubectl delete -f network
kubectl delete pvc data-bootnode-1-0
kubectl delete pvc data-validator-1-0
kubectl delete pvc data-validator-2-0
kubectl delete pvc data-validator-3-0
kubectl delete pvc data-validator-4-0
