apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "besu.fullname" . }}-pvc
  labels:
    {{- include "besu.labels" . | nindent 4 }}
spec:
  accessModes: {{ .Values.persistence.accessModes }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}