apiVersion: v1
kind: Secret
metadata:
  name: {{ include "besu.fullname" . }}-secret
  labels:
    {{- include "besu.labels" . | nindent 4 }}
stringData:
  key: {{ .Values.nodePrivateKey | trim | quote }}
