apiVersion: v1
kind: Service
metadata:
  name: {{ include "besu.fullname" . }}
  labels:
    {{- include "besu.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rlpx
      port: {{ .Values.config.p2pPort }}
    - name: discport
      port: {{ .Values.config.p2pPort }}
      protocol: UDP
    - name: rpc-http
      port: {{ .Values.config.rpcHttpPort }}
    - name: rpc-ws
      port: {{ .Values.config.rpcWsPort }}
    - name: graphql-http
      port: {{ .Values.config.graphqlHttpPort }}
  selector:
    {{- include "besu.selectorLabels" . | nindent 4 }}
