apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sirato-free.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sirato-free.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    matchLabels:
      {{- include "sirato-free.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  #replicas: 1 #default
  #minReadySeconds: 0 #default
  template:
    metadata:
      labels:
        {{- include "sirato-free.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      #serviceAccountName: {{ include "sirato-free.fullname" . }}-api
      #terminationGracePeriodSeconds: 10
      containers:
      - name: api
        image: web3labs/epirus-free-api
        ports:
        - containerPort: 8090
        env:
        - name: MONGO_CLIENT_URI
          value: "mongodb://{{ include "sirato-free.fullname" . }}-db"
        - name: MONGO_DB_NAME
          value: epirus
        - name: MONGO_CREATE_INDICES
          value: "true"
        - name: NODE_ENDPOINT
          value: "http://{{ .Values.network.name }}-{{ .Values.sirato.targetNode.name }}:8545"
        - name: REINDEX_ENDPOINT
          value: "http://{{ include "sirato-free.fullname" . }}-ingestion:8095/reindex"