apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.network.name }}-sirato-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sirato-free.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  clusterIP: None
  selector:
    {{- include "sirato-free.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
  - port: 8090
    name: api