apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.network.name }}-sirato-api
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: {{ .Release.Name }}
  #replicas: 1 #default
  #minReadySeconds: 0 #default
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      #serviceAccountName: sirato-api-sa
      #terminationGracePeriodSeconds: 10
      containers:
      - name: api
        image: web3labs/epirus-free-api
        ports:
        - containerPort: 8090
        env:
        - name: MONGO_CLIENT_URI
          value: "mongodb://{{ .Values.network.name }}-sirato-db"
        - name: MONGO_DB_NAME
          value: epirus
        - name: MONGO_CREATE_INDICES
          value: "true"
        - name: NODE_ENDPOINT
          value: "http://{{ .Values.network.name }}-{{ .Values.sirato.targetNode.name }}:8545"
        - name: REINDEX_ENDPOINT
          value: "http://{{ .Values.network.name }}-sirato-ingestion:8095/reindex"