apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.network.name }}-sirato-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sirato-free.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  clusterIP: None
  selector:
    {{- include "sirato-free.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: db
  ports:
  - port: 27017
    name: db