apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.network.name }}-sirato-db
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: db
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  serviceName: {{ .Values.network.name }}-sirato-db
  selector:
    matchLabels:
      app.kubernetes.io/name: db
      app.kubernetes.io/instance: {{ .Release.Name }}
  #replicas: 1 #default
  #minReadySeconds: 0 #default
  template:
    metadata:
      labels:
        app.kubernetes.io/name: db
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      #serviceAccountName: sirato-db-sa
      #terminationGracePeriodSeconds: 10
      containers:
      - name: db
        image: mongo
        ports:
        - containerPort: 27017
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: ["ReadWriteOnce"]
      {{- if .Values.sirato.storageClassName }}
      storageClassName: {{ .Values.sirato.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.sirato.storage }}
