apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sirato-free.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sirato-free.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  serviceName: {{ include "sirato-free.fullname" . }}-db
  selector:
    matchLabels:
      {{- include "sirato-free.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: db
  #replicas: 1 #default
  #minReadySeconds: 0 #default
  template:
    metadata:
      labels:
        {{- include "sirato-free.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: db
    spec:
      #serviceAccountName: {{ include "sirato-free.fullname" . }}-db
      #terminationGracePeriodSeconds: 10
      {{- with .Values.sirato.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sirato.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sirato.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: db
        image: mongo
        ports:
        - containerPort: 27017
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      {{- if .Values.sirato.storageClassName }}
      storageClassName: {{ .Values.sirato.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.sirato.storage }}
