apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.network.name }}-sirato-ingestion
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ingestion
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingestion
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  #replicas: 1 #default
  #minReadySeconds: 0 #default
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingestion
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      #serviceAccountName: sirato-ingestion-sa
      #terminationGracePeriodSeconds: 10
      containers:
      - name: ingestion
        image: web3labs/epirus-free-ingestion
        ports:
        - containerPort: 8095
        env:
        - name: MONGO_CLIENT_URI
          value: "mongodb://{{ .Values.network.name }}-sirato-db"
        - name: MONGO_DB_NAME
          value: epirus
        - name: NODE_ENDPOINT
          value: "http://{{ .Values.network.name }}-{{ .Values.sirato.targetNode.name }}:8545"