apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.network.name }}-sirato-ingestion
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sirato-free.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingestion
spec:
  clusterIP: None
  selector:
    {{- include "sirato-free.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ingestion
  ports:
  - port: 8095
    name: ingestion