apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.network.name }}-sirato-ingestion
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sirato-free.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingestion
spec:
  selector:
    matchLabels:
      {{- include "sirato-free.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ingestion
  #replicas: 1 #default
  #minReadySeconds: 0 #default
  template:
    metadata:
      labels:
        {{- include "sirato-free.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ingestion
    spec:
      #serviceAccountName: sirato-ingestion-sa
      #terminationGracePeriodSeconds: 10
      containers:
      - name: ingestion
        image: web3labs/epirus-free-ingestion
        ports:
        - containerPort: 8095
        env:
        - name: MONGO_CLIENT_URI
          value: "mongodb://{{ .Values.network.name }}-sirato-db"
        - name: MONGO_DB_NAME
          value: epirus
        - name: NODE_ENDPOINT
          value: "http://{{ .Values.network.name }}-{{ .Values.sirato.targetNode.name }}:8545"