apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.network.name }}-sirato-ingestion
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ingestion
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: ingestion
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  ports:
  - port: 8095
    name: ingestion