apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.network.name }}-sirato-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: proxy
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: proxy
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      containers:
      - name: proxy
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx
          name: nginx-conf
          readOnly: true
        - mountPath: /var/log/nginx
          name: log
        - mountPath: /www/error_pages
          name: error-pages
          readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: {{ .Values.network.name }}-sirato-proxy
          items:
            - key: nginx.conf
              path: nginx.conf
      - name: log
        emptyDir: {}
      - name: error-pages
        configMap:
          name: {{ .Values.network.name }}-sirato-proxy
          items:
            - key: 5xx.html
              path: 5xx.html