apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sirato-free.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sirato-free.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    matchLabels:
      {{- include "sirato-free.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  #replicas: 1 #default
  #minReadySeconds: 0 #default
  template:
    metadata:
      labels:
        {{- include "sirato-free.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      #serviceAccountName: {{ include "sirato-free.fullname" . }}-web
      #terminationGracePeriodSeconds: 10
      containers:
      - name: web
        image: web3labs/epirus-free-web
        ports:
        - containerPort: 3000
        env:
        - name: API_URL
          value: /api