apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.network.name }}-sirato-web
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: web
      app.kubernetes.io/instance: {{ .Release.Name }}
  #replicas: 1 #default
  #minReadySeconds: 0 #default
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      #serviceAccountName: sirato-web-sa
      #terminationGracePeriodSeconds: 10
      containers:
      - name: web
        image: web3labs/epirus-free-web
        ports:
        - containerPort: 3000
        env:
        - name: API_URL
          value: /api