apiVersion: v1
kind: Service
metadata:
  name: {{ include "sirato-free.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sirato-free.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  clusterIP: None
  selector:
    {{- include "sirato-free.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
  - port: 3000
    name: web